
VLIB_MACRO_NAME 	:=
VLIB_MACRO_IN_LIB 	:=
VLIB_ITG_DRV_MACROS	:=
VLIB_ITG_USR_MACROS	:=
VLIB_RIVP_USR_MACROS :=
VLIB_INC 			:=
VLIB_VPATH 			:=
VLIB_LIB_VPATH 		:=
VLIB_COMMONFLAGS	:=
VLIB_CFLAGS			:=
VLIB_ASFLAGS		:=
VLIB_LDFLAGS		:=
VLIB_DEFINE			:=
VLIB_APP_DIR		:= $(shell pwd)
VLIB_BSP_DRIVER		:=
VLIB_USE_OWN_SETUP	:= 
VLIB_DBG_PRINT_REGS := 
VLIB_MIDDLEWARE		:= 
VLIB_RENESAS_MISRA  :=
VLIB_MISRA			:=
VLIB_RENESAS_MISRA_STRICT :=
 
