#include "r_typedefs.h"

typedef enum
{
	//TT SHORT TO BATTERY
	DTC_SYSTEM_CHECK_ENGINE_TT_STB_A002,    /*0*/
	DTC_MIL_TT_STB_A003,					/*1*/
	DTC_ENG_ST_SP_TT_STB_A009,
	DTC_ABS_TT_STB_A00A,
	DTC_CRUISE_TT_STB_A00B,
	DTC_AIRBAG_TT_STB_A00C,
	DTC_PARKBRAKE_TT_STB_A00D,
	DTC_EPS_TT_STB_A00E,
	DTC_ATFAIL_TT_STB_A010,
	DTC_ESP_TT_STB_A01A,
	//DTC_ESP_ACTIVE_TT_FAIL_A01A,
#if 0
	//TT SHORT TO GROUND
	DTC_SYSTEM_CHECK_ENGINE_TT_STG_A002,
	DTC_MIL_TT_STG_A003,
	DTC_ENG_ST_SP_TT_STG_A009,
	DTC_ABS_TT_STG_A00A,
	DTC_CRUISE_TT_STG_A00B,
	DTC_AIRBAG_TT_STG_A00C,
	DTC_PARKBRAKE_TT_STG_A00D,
	DTC_EPS_TT_STG_A00E,
	DTC_ATFAIL_TT_STG_A010,
	DTC_ESP_TT_STG_A01A,
#endif
	//lvsd/hvsd
	DTC_HVSD_A000,
	DTC_LVSD_A000,

	//Switch
//	DTC_BUTTON_STUCK_A000,
	DTC_MODE_SWITCH_STUCK_A01C,
	DTC_OK_SWITCH_STUCK_A01D,
	DTC_UP_SWITCH_STUCK_A01E,
	DTC_DOWN_SWITCH_STUCK_A01F,
	DTC_SET_SWITCH_STUCK_A022,

	//MEMEORY
	DTC_ROM_FAIL_A001,
	DTC_RAM_FAIL_A001,
	DTC_EEPROM_FAIL_A001,

	//FUEL
	DTC_FUEL_OC_FAIL_A004,
	DTC_FUEL_SC_FAIL_A004,

	//WDT
	DTC_WDT_RST_FAIL_A012,

	//CONFIGURATION
	DTC_CONFIG_CURR_FAIL_A014,
	DTC_HELTH_MONTR_FAIL_A015,

	//Clock oscillator outside acceptable range
	DTC_CLOCK_OCC_FAIL_A016,

	//NODE ABSENT
	DTC_EMS_NODEABSENT_D101,
	DTC_TCU_NODEABSENT_D102,
	DTC_ABS_ESC_NODEABSENT_D103,
	DTC_MBFM_NODEABSENT_D104,
	DTC_SRS_NODEABSENT_D106,
	DTC_IS_NODEABSENT_D108,
	DTC_SAS_NODEABSENT_D110,
	DTC_ICU_NODEABSENT_D117,
	DTC_PKE_NODEABSENT_D130,
	DTC_RPAS_NODEABSENT_D112,

	//MESSAGE TIMEOUT
	DTC_EMS_MSGTIMEOUT_D001,
	DTC_TCU_MSGTIMEOUT_D002,
	DTC_ABS_ESC_MSGTIMEOUT_D003,
	DTC_MBFM_MSGTIMEOUT_D004,
	DTC_IS_MSGTIMEOUT_D008,
	DTC_PKE_MSGTIMEOUT_D030,
	DTC_RPAS_MSGTIMEOUT_D012,

	//BUS OFF
	DTC_IC_BUSOFF_D205,

	//MESSAGE CONTENT FAILURE
	DTC_EMS1_10_MSGCONTFAIL_E401,
	DTC_EMS6_500_MSGCONTFAIL_E406,
	DTC_EMS3_10_MSGCONTFAIL_E403,
	DTC_EMS4_20_MSGCONTFAIL_E404,
	DTC_EMS8_10_MSGCONTFAIL_E407,
	DTC_EMS12_200_MSGCONTFAIL_E409,
	DTC_EMS29_100_MSGCONTFAIL_E43A,
	DTC_EMS36_10_MSGCONTFAIL_E4A2,
	DTC_ESC2_10_MSGCONTFAIL_E40D,
	DTC_ESC5_10_MSGCONTFAIL_E420,
	DTC_ESC12_10_MSGCONTFAIL_E4AE,
	DTC_MBFM1_100_MSGCONTFAIL_E40F,
	DTC_MBFM5_100_MSGCONTFAIL_E410,
	DTC_SRS1_20_MSGCONTFAIL_E415,
	DTC_IS1_100_MSGCONTFAIL_E416,
	DTC_IS3_500_MSGCONTFAIL_E485,
	DTC_IS4_500_MSGCONTFAIL_E4AD,
	DTC_TCU5_10_MSGCONTFAIL_E4AF,
	DTC_TCU6_20_MSGCONTFAIL_E4B0,
	DTC_PKE_ICU2_100_MSGCONTFAIL_E418,
	DTC_SAS1_10_MSGCONTFAIL_E426,
	DTC_ESC7_20_MSGCONTFAIL_E484,
	DTC_MBFM6_100_MSGCONTFAIL_E411,
	DTC_MBFM7_100_MSGCONTFAIL_E412,
	DTC_MBFM9_500_MSGCONTFAIL_E4BA,
	DTC_MBFM_PAS1_50_MSGCONTFAIL_E4B8,
	DTC_RPAS1_20_MSGCONTFAIL_E437,
	DTC_RPAS2_100_MSGCONTFAIL_E438,

	//IVN
	DTC_IVN_MISMATCH_D305,
	DTC_IVN_VARIENT_ERR_D505,
	DTC_IVN_FEATURE_ERR_E805,
	DTC_IVN_NETSECFAULT_E5FF,
	DTC_IVN_NETSECCONFFAULT_E5FE,

	//SIGNAL CONTENT FAILURE
	DTC_EMS_GEAR_SIGNAL_CONTFAIL_E003,
	DTC_EMS_RPM_SIGNAL_CONTFAIL_E004,
	DTC_EMS_ENG_TEMP_SIGNAL_CONTFAIL_E008,
	DTC_EMS_CLUCH_SIGNAL_CONTFAIL_E009,
	DTC_EMS_TARGET_GEAR_SIGNAL_CONTFAIL_E074,
	DTC_EMS_INDC_CRUISE_SIGNAL_CONTFAIL_E055,
	DTC_DISP_AMBT_TEMP_EMS_SIGNAL_CONTFAIL_E0BE,
	DTC_ABS_VEH_SPEED_SIGNAL_CONTFAIL_E013,
	DTC_ABS_ODO_DIST_SIGNAL_CONTFAIL_E014,
//	DTC_AIRBAG_EVEN_PARITY_SIGNAL_CONTFAIL_E015,
	DTC_MBFM_ENGOFF_SIGNAL_CONTFAIL_E018,
	DTC_TCU_GEAR_ACTUAL_SIGNAL_CONTFAIL_E072,
	DTC_TCU_TGS_LEVER_SIGNAL_CONTFAIL_E073,
	DTC_SAS_ABOLUTE_ANGLE_SIGNAL_CONTFAIL_E058,
	DTC_ENG_TRQ_AFTER_RED1_SIGNAL_CONTFAIL_E011,
	DTC_ENG_DRIVE_MODE_SIGNAL_CONTFAIL_E09B,
	DTC_YAW_RATE_SIGNAL_CONTFAIL_E059,
	DTC_LONG_ACCEL_SIGNAL_CONTFAIL_E054,
	DTC_LATTERAL_ACCEL_SIGNAL_CONTFAIL_E053,
	DTC_RPAS_DISP_DIST_SIGNAL_CONTFAIL_E0E3,
	DTC_INDC_SRS_SIGNAL_CONTFAIL_E0D0,
	DTC_TGS_MODE_SIGNAL_CONTFAIL_E0E0,
	DTC_GEAR_TARGET_SIGNAL_CONTFAIL_E0CA,
	DTC_INDC_AT_MALFUNC_SIGNAL_CONTFAIL_E0DF,
	DTC_FL_TYRE_PRESSURE_SIGNAL_CONTFAIL_E0D6,
	DTC_FR_TYRE_PRESSURE_SIGNAL_CONTFAIL_E0D7,
	DTC_RL_TYRE_PRESSURE_SIGNAL_CONTFAIL_E0D8,
	DTC_RR_TYRE_PRESSURE_SIGNAL_CONTFAIL_E0D9,
	DTC_STS_ESS_INDC_SIGNAL_CONTFAIL_E0AD,
	

	//BUS INTRGRITY FAILURE
	DTC_MBFM_BUS_INTRGRITY_FAIL_D801,
	DTC_PKE_BUS_INTRGRITY_FAIL_D800,
}DTC_ID;


extern _Bool CAN_Bus_Off;
extern _Bool clear_dtc_log_flag;

extern void read_dtcs(void);
extern void clear_dtcs(void);
extern void Dtc_init(void);
extern void Read_DTC_Status(void);
extern void All_DTC_Write(void);
extern void telltale_failure_DTC_Set(uint16_t i);
extern void telltale_failure_DTC_Clear(uint16_t i);
extern void message_timeout_DTC_Clear(uint16_t i);
extern void message_timeout_DTC_Set(uint16_t i);
extern void Node_Absent_DTC_Set(uint16_t i);
extern void Node_Absent_DTC_Clear(uint16_t i);
extern void Message_Content_Failure_DTC_Set(uint16_t i);
extern void Message_Content_Failure_DTC_Clear(uint16_t i);
extern void voltage_Failure_DTC_Set(uint16_t i);
extern void voltage_Failure_DTC_Clear(uint16_t i);
extern void Failure_DTC_Set(uint16_t i);
extern void Failure_DTC_Clear(uint16_t i);
extern void can_bus_off_failure_detection(void);
extern void can_bus_off_failure_DTC(uint16_t i);
extern void Set_Clear_IVN_DTC(void);
extern void Freeze_Frame_log(uint16_t eeprom_offset);
extern void Clear_IVN_Variables(void);
extern void Clear_EEPROM_DTC_Memory(void);
