/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Inline function bodies
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 3935 $
 *  $Date: 2014-09-23 10:52:32 +0200 (Di, 23. Sep 2014) $
 *  $LastChangedBy: golczewskim $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/    

#ifndef DAVEHD_DRIVER_INL_H_INCLUDED
#define DAVEHD_DRIVER_INL_H_INCLUDED

/*----------------------------------------------------------------------------------------------------------*/
#include "davehd_internal.h"

/*----------------------------------------------------------------------------------------------------------*/
/* State functions */
/**/
#include "davehd_driver_blu_inl.h"    /* Blend Unit related functions*/
#include "davehd_driver_col_inl.h"    /* Color Unit related functions*/
#include "davehd_driver_psu_inl.h"    /* Pixel Selection related functions*/
#include "davehd_driver_txp_inl.h"    /* Texture Unit related functions*/
#include "davehd_driver_zsu_inl.h"    /* ZSA Unit related functions*/
#include "davehd_driver_buf_inl.h"    /* Buffer related functions*/

/*----------------------------------------------------------------------------------------------------------*/
/* Utility functions */
/**/
#include "davehd_util_inl.h" 

/*----------------------------------------------------------------------------------------------------------*/

#endif /*DAVEHD_DRIVER_INL_H_INCLUDED*/
